version: '3.8'

services:
  ohif-viewer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    restart: always

  orthanc:
    image: orthancteam/orthanc
    ports:
      - '4242:4242'
      - '8042:8042'
    restart: always
